# Generated by Django 5.1.3 on 2024-12-09 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='product_id',
        ),
    ]
