# Generated by Django 5.1.4 on 2024-12-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haircare_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='hair_Category',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='hair_Product',
        ),
        migrations.RenameModel(
            old_name='Review',
            new_name='hair_Review',
        ),
    ]
