# Generated by Django 5.1.4 on 2024-12-09 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                ("product_id", models.IntegerField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=255, unique=True)),
                ("image_url", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="review",
            fields=[
                ("review_id", models.IntegerField(primary_key=True, serialize=False)),
                ("review_data", models.TextField()),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthy.product",
                    ),
                ),
            ],
        ),
    ]
